[tool.isort]
profile = "black"
src_paths = ["src", "tests"]
honor_noqa = true

[tool.pytest.ini_options]
addopts = "--doctest-modules"
doctest_optionflags = "NORMALIZE_WHITESPACE ELLIPSIS"
minversion = "6.2"
testpaths = ["tests"]
pythonpath = ["src"]
asyncio_mode = "auto"
asyncio_default_fixture_loop_scope = "function"


[tool.pylint.'MESSAGES CONTROL']
max-line-length = 120
disable = """
    missing-function-docstring,
    missing-module-docstring,
    missing-class-docstring,
"""
